// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw4pSQAJCmsHNKVBl-U9P5buCBGAo8OOA',
    appId: '1:688400492651:web:5b28d8d52da8a0839ca92e',
    messagingSenderId: '688400492651',
    projectId: 'push-notification-flutte-79336',
    authDomain: 'push-notification-flutte-79336.firebaseapp.com',
    storageBucket: 'push-notification-flutte-79336.appspot.com',
    measurementId: 'G-V2P18L4GBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUd4mWJNWkQv9tC4SyK0TQfZvxukHpJzk',
    appId: '1:688400492651:android:2d5393ce752b99329ca92e',
    messagingSenderId: '688400492651',
    projectId: 'push-notification-flutte-79336',
    storageBucket: 'push-notification-flutte-79336.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD5I2bMsoUJZxmPE1xbqNI3w5qDUNrRu0',
    appId: '1:688400492651:ios:8d4384001cda52629ca92e',
    messagingSenderId: '688400492651',
    projectId: 'push-notification-flutte-79336',
    storageBucket: 'push-notification-flutte-79336.appspot.com',
    iosClientId: '688400492651-i7vghae8qhg72pmgnb92c6j3tg3jpbtj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationApp',
  );
}
